language: cpp
sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang

install:
  - ./install_gtest.sh
script:
  - ./build.sh
after_success:
  - ./codecov.sh
